### ISSUE TITLE
Preventing DB Query

### ISSUE THREAD

**Issue by Drew-Dix** [interconnectit/wp-permastructure#8]
The WP Permalinks plugin appears to be preventing a database query to complete. This came to light when Yoast was reviewing the install and the site maps were not being generated correctly due to this issue. They noted there exists a workaround available here: https://github.com/Yoast/wordpress-seo/issues/7763

Is this something that will (or can) be addressed?

**Comment by nasyrov** [comment]
Hi @Drew-Dix,

The fix is already in place, please update your plugin from the master.
